import { Vector3 } from "three";

/** Conversion constant from radians to degrees */
const RAD2DEG = 180 / Math.PI;

/** Reusable Vector3 to avoid allocations */
const tempVector3 = new Vector3();

/**
 * Generates a random point on a sphere surface
 * @param origin Center point of the sphere
 * @param radius Radius of the sphere
 * @param target Optional Vector3 to store result
 * @returns Vector3 containing random point coordinates
 */
function randomSpherePointVector3(
  origin: Vector3,
  radius: number,
  target: Vector3 = new Vector3(),
): Vector3 {
  const { x: x0, y: y0, z: z0 } = origin;
  const u = Math.random();
  const v = Math.random();
  const theta = 2 * Math.PI * u;
  const phi = Math.acos(2 * v - 1);

  const x = x0 + radius * Math.sin(phi) * Math.cos(theta);
  const y = y0 + radius * Math.sin(phi) * Math.sin(theta);
  const z = z0 + radius * Math.cos(phi);

  return target.set(x, y, z);
}

/**
 * Generates a random latitude/longitude pair
 * @returns New LatLong with random coordinates
 */
function getRandomLatLong(): LatLong {
  return LatLong.cartesianToLatLong(randomSpherePointVector3(tempVector3, 100));
}

/**
 * Represents a geographic coordinate using latitude and longitude
 * Provides utilities for converting between spherical and Cartesian coordinates
 */
export class LatLong {
  /**
   * Creates a new LatLong instance
   * @param lat Latitude in degrees (-90 to 90)
   * @param lon Longitude in degrees (-180 to 180)
   */
  constructor(
    public lat: number = 0,
    public lon: number = 0,
  ) {}

  /**
   * Creates a string hash from latitude/longitude pair
   */
  static hash(lat: number, lon: number): number {
    // Convert lat/lon to integers with 6 decimal precision
    const latInt = Math.round((lat + 90) * 1e6);
    const lonInt = Math.round((lon + 180) * 1e6);
    // Combine into single number, lat in upper 32 bits, lon in lower
    return latInt * 1e9 + lonInt;
  }

  /** Gets the string hash representation */
  get hash(): number {
    return LatLong.hash(this.lat, this.lon);
  }

  /**
   * Converts a numeric hash back into a LatLong instance
   * @param hash - The numeric hash generated by LatLong.hash()
   * @returns A new LatLong instance with the decoded coordinates
   *
   * The hash format stores:
   * - Latitude in upper bits: ((lat + 90) * 1e6) * 1e9
   * - Longitude in lower bits: (lon + 180) * 1e6
   */
  static parseHash(hash: number): LatLong {
    const lat = hash / 1e9 - 90;
    const lon = (hash % 1e9) - 180;
    return new LatLong(lat, lon);
  }

  /** String representation of coordinates */
  toString(): string {
    return `${this.lat}:${this.lon}`;
  }

  /**
   * Creates a LatLong from a hash string
   * @param hash String in format "lat:lon"
   */
  static parseString(hash: string): LatLong {
    return new LatLong(...hash.split(":").map((n) => parseFloat(n)));
  }

  /**
   * Calculates Euclidean distance to another LatLong
   * Note: This is not a geodesic distance
   */
  distanceTo(other: LatLong): number {
    return Math.sqrt((this.lat - other.lat) ** 2 + (this.lon - other.lon) ** 2);
  }

  /** Creates a copy of this LatLong */
  clone(): LatLong {
    return new LatLong(this.lat, this.lon);
  }

  /**
   * Copies values from another LatLong
   * @returns this for chaining
   */
  copy(latLong: LatLong): this {
    this.lat = latLong.lat;
    this.lon = latLong.lon;
    return this;
  }

  /**
   * Sets new latitude and longitude values
   * @returns this for chaining
   */
  set(lat: number, lon: number): this {
    this.lat = lat;
    this.lon = lon;
    return this;
  }

  /** Creates a LatLong with random coordinates */
  static random(): LatLong {
    return getRandomLatLong();
  }

  /**
   * Converts spherical coordinates to Cartesian (x,y,z)
   * @param radius Sphere radius
   * @param vec3 Vector3 to store result
   * @returns Modified vec3 parameter
   */
  toCartesian(radius: number, vec3: Vector3): Vector3 {
    const phi = ((90 - this.lat) * Math.PI) / 180;
    const theta = ((90 - this.lon) * Math.PI) / 180;

    return vec3.set(
      radius * Math.sin(phi) * Math.cos(theta), // x
      radius * Math.cos(phi), // y
      radius * Math.sin(phi) * Math.sin(theta), // z
    );
  }

  /**
   * Converts Cartesian coordinates to latitude/longitude
   * @param coordinates Vector3 containing Cartesian coordinates
   * @returns this for chaining
   */
  cartesianToLatLong(coordinates: Vector3): LatLong {
    const longitude = Math.atan2(coordinates.x, coordinates.z) * RAD2DEG;
    const length = Math.sqrt(coordinates.x * coordinates.x + coordinates.z * coordinates.z);
    const latitude = Math.atan2(coordinates.y, length) * RAD2DEG;

    this.lat = latitude;
    this.lon = longitude;
    return this;
  }

  /**
   * Static version of cartesianToLatLong that creates a new LatLong
   * @param coordinates Vector3 containing Cartesian coordinates
   * @param latLong Optional LatLong to store result
   * @returns New or modified LatLong instance
   */
  static cartesianToLatLong(coordinates: Vector3, latLong: LatLong = new LatLong()): LatLong {
    const longitude = Math.atan2(coordinates.x, coordinates.z) * RAD2DEG;
    const length = Math.sqrt(coordinates.x * coordinates.x + coordinates.z * coordinates.z);
    const latitude = Math.atan2(coordinates.y, length) * RAD2DEG;

    latLong.lat = latitude;
    latLong.lon = longitude;
    return latLong;
  }
}
